### ISSUE TITLE
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

### ISSUE THREAD

**Issue by Skid888** [Haoming02/sd-webui-old-photo-restoration#16]
I've installed BOP (and overcome the dlib install issue) but still get the following error:

calling C:\Users\Söhnke\stable-diffusion-webui\extensions\sd-webui-old-photo-restoration\scripts\bop.py/ui: AttributeError
Traceback (most recent call last):
  File "C:\Users\Söhnke\stable-diffusion-webui\modules\scripts_postprocessing.py", line 53, in wrap_call
    res = func(*args, **kwargs)
  File "C:\Users\Söhnke\stable-diffusion-webui\extensions\sd-webui-old-photo-restoration\scripts\bop.py", line 12, in ui
    with ui_components.InputAccordion(
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

Traceback (most recent call last):
  File "C:\Users\Söhnke\stable-diffusion-webui\launch.py", line 353, in <module>
    start()
  File "C:\Users\Söhnke\stable-diffusion-webui\launch.py", line 348, in start
    webui.webui()
  File "C:\Users\Söhnke\stable-diffusion-webui\webui.py", line 302, in webui
    shared.demo = modules.ui.create_ui()
  File "C:\Users\Söhnke\stable-diffusion-webui\modules\ui.py", line 1051, in create_ui
    ui_postprocessing.create_ui()
  File "C:\Users\Söhnke\stable-diffusion-webui\modules\ui_postprocessing.py", line 25, in create_ui
    script_inputs = scripts.scripts_postproc.setup_ui()
  File "C:\Users\Söhnke\stable-diffusion-webui\modules\scripts_postprocessing.py", line 113, in setup_ui
    self.create_script_ui(script, inputs)
  File "C:\Users\Söhnke\stable-diffusion-webui\modules\scripts_postprocessing.py", line 84, in create_script_ui
    for control in script.controls.values():
AttributeError: 'NoneType' object has no attribute 'values'

Any idea where the issue comes from?

**Comment by Haoming02** [comment]
> 'modules.ui_components' has no attribute 'InputAccordion'

What version of Webui are you running?

**Comment by Skid888** [comment]
Webui is 1.6.0

**Comment by Skid888** [comment]
I just updated to 1.8.0 and now it is working!
