### ISSUE TITLE
AssertionError with Face restore checked

### ISSUE THREAD

**Issue by TorAllex** [Haoming02/sd-webui-old-photo-restoration#19]
Running Stage 3: Face Enhancement
Dataset [FaceTestDataset] with 2 faces was created...
The size of the latent vector size is [8,8]
Network [SPADEGenerator] was created. Total number of parameters: 92.1 million.
*** Error completing request
*** Arguments: ('task(fs5h6ayzx6r48se)', 0.0, <PIL.Image.Image image mode=RGBA size=900x1256 at 0x171E02810>, None, '', '', True, True, 0.0, 1, 0.0, 1024, 1024, True, 'R-ESRGAN 4x+', 'None', 0, False, 1, False, 1, 0, False, 0.5, 0.2, False, 0.9, 0.15, 0.5, False, False, 384, 768, 4096, 409600, 'Maximize area', 0.1, False, ['Horizontal'], False, ['Deepbooru'], True, 'Restoration First', False, True, False) {}
    Traceback (most recent call last):
      File "/Users/alex/stable-diffusion-webui/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/stable-diffusion-webui/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/stable-diffusion-webui/modules/postprocessing.py", line 131, in run_postprocessing_webui
        return run_postprocessing(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/stable-diffusion-webui/modules/postprocessing.py", line 71, in run_postprocessing
        scripts.scripts_postproc.run(initial_pp, args)
      File "/Users/alex/stable-diffusion-webui/modules/scripts_postprocessing.py", line 185, in run
        script.process_firstpass(pp, **process_args)
      File "/Users/alex/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/scripts/bop.py", line 46, in process_firstpass
        pp.image = main(img, do_scratch, is_hr, do_face_res)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/scripts/main_function.py", line 111, in main
        restored_faces = test_face(faces, args)
                         ^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/Face_Enhancement/test_face.py", line 22, in test_face
        model = Pix2PixModel(opt)
                ^^^^^^^^^^^^^^^^^
      File "/Users/alex/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/Face_Enhancement/models/pix2pix_model.py", line 21, in __init__
        self.netG, self.netD, self.netE = self.initialize_networks(opt)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/Face_Enhancement/models/pix2pix_model.py", line 84, in initialize_networks
        netG = networks.define_G(opt)
               ^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/Face_Enhancement/models/networks/__init__.py", line 47, in define_G
        return create_network(netG_cls, opt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/alex/stable-diffusion-webui/extensions/sd-webui-old-photo-restoration/Face_Enhancement/models/networks/__init__.py", line 39, in create_network
        assert torch.cuda.is_available()
    AssertionError

**Comment by Haoming02** [comment]
Hmm. What GPU do you have?

**Comment by TorAllex** [comment]
Ok, it's working now. Any chance for AMD's GPU support?

**Comment by Haoming02** [comment]
Realistically, the speed is not that much slower when running on CPU.
As for AMD, IDK how it works with PyTorch.
