### ISSUE TITLE
cant install "dlib"  on forge webui

### ISSUE THREAD

**Issue by dongxiat** [Haoming02/sd-webui-old-photo-restoration#23]
> To create a public link, set `share=True` in `launch()`.
Startup time: 45.4s (prepare environment: 6.4s, import torch: 3.8s, import gradio: 1.0s, setup paths: 2.9s, initialize shared: 0.1s, other imports: 0.7s, load scripts: 12.3s, scripts list_optimizers: 0.1s, create ui: 17.4s, gradio launch: 0.6s).
*** Error running install.py for extension D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\webui\extensions\sd-webui-old-photo-restoration.
*** Command: "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\python.exe" "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\webui\extensions\sd-webui-old-photo-restoration\install.py"
*** Error code: 1
*** stdout: Installing Old-Photo-Restoration Requirement: dlib
***
*** stderr: Traceback (most recent call last):
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\webui\extensions\sd-webui-old-photo-restoration\install.py", line 14, in <module>
***     launch.run_pip(f"install {package}", f"Old-Photo-Restoration Requirement: {package}")
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 152, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\webui\modules\launch_utils.py", line 124, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install Old-Photo-Restoration Requirement: dlib.
*** Command: "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\python.exe" -m pip install dlib --prefer-binary
*** Error code: 2
*** stdout: Collecting dlib
***   Using cached dlib-19.24.4.tar.gz (3.3 MB)
***   Installing build dependencies: started
***   Installing build dependencies: finished with status 'done'
***   Getting requirements to build wheel: started
***   Getting requirements to build wheel: finished with status 'done'
***
*** stderr: ERROR: Exception:
*** Traceback (most recent call last):
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
***     status = run_func(*args)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
***     return func(self, options, args)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
***     requirement_set = resolver.resolve(
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
***     result = self._result = resolver.resolve(
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
***     state = resolution.resolve(requirements, max_rounds=max_rounds)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
***     self._add_to_criteria(self.state.criteria, r, parent=None)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
***     if not criterion.candidates:
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
***     return bool(self._sequence)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
***     return any(self)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
***     return (c for c in iterator if id(c) not in self._incompatible_ids)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
***     candidate = func()
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 182, in _make_candidate_from_link
***     base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
***     self._link_candidate_cache[link] = LinkCandidate(
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 290, in __init__
***     super().__init__(
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
***     self.dist = self._prepare()
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 222, in _prepare
***     dist = self._prepare_distribution()
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 301, in _prepare_distribution
***     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 525, in prepare_linked_requirement
***     return self._prepare_linked_requirement(req, parallel_builds)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 640, in _prepare_linked_requirement
***     dist = _get_prepared_distribution(
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\operations\prepare.py", line 71, in _get_prepared_distribution
***     abstract_dist.prepare_distribution_metadata(
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 54, in prepare_distribution_metadata
***     self._install_build_reqs(finder)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 124, in _install_build_reqs
***     build_reqs = self._get_build_requires_wheel()
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\distributions\sdist.py", line 101, in _get_build_requires_wheel
***     return backend.get_requires_for_build_wheel()
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_internal\utils\misc.py", line 745, in get_requires_for_build_wheel
***     return super().get_requires_for_build_wheel(config_settings=cs)
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 166, in get_requires_for_build_wheel
***     return self._call_hook('get_requires_for_build_wheel', {
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_impl.py", line 321, in _call_hook
***     raise BackendUnavailable(data.get('traceback', ''))
*** pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
***     obj = import_module(mod_path)
***   File "importlib\__init__.py", line 126, in import_module
***   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
***   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
***   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
***   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
***   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
***   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
***   File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-yvkzszgl\overlay\Lib\site-packages\setuptools\__init__.py", line 8, in <module>
***     import _distutils_hack.override  # noqa: F401
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
***     __import__('_distutils_hack').do_override()
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\_distutils_hack\__init__.py", line 77, in do_override
***     ensure_local_distutils()
***   File "D:\SOFTWARE\AI\StableDiffusion\webui_forge_cu121_torch21\system\python\lib\site-packages\_distutils_hack\__init__.py", line 63, in ensure_local_distutils
***     core = importlib.import_module('distutils.core')
***   File "importlib\__init__.py", line 126, in import_module
***   File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-yvkzszgl\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 14, in <module>
***     from .config import PyPIRCCommand
***   File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-yvkzszgl\overlay\Lib\site-packages\setuptools\_distutils\config.py", line 7, in <module>
***     import email.message
***   File "email\message.py", line 15, in <module>
***   File "email\utils.py", line 29, in <module>
***   File "socket.py", line 51, in <module>
*** ModuleNotFoundError: No module named '_socket'
***
***
*** [notice] A new release of pip is available: 24.0 -> 24.1
*** [notice] To update, run: python.exe -m pip install --upgrade pip
***

I make sure Visual Studio 2022 with C++ and CMake already install
![image](https://github.com/Haoming02/sd-webui-old-photo-restoration/assets/75362901/5ea9433f-1a02-4835-8cb7-97b92e4f11d6)
![image](https://github.com/Haoming02/sd-webui-old-photo-restoration/assets/75362901/b92e187a-eed2-4e94-ba22-67f3915b1974)

**Comment by dongxiat** [comment]
i found the way out if you use SDWebui-Forge do below to install `dlib `manually

1. go to >> https://github.com/z-mahmud22/Dlib_Windows_Python3.x/tree/main
2. choose `dlib `for python version 3.10 (Forge) >> https://github.com/z-mahmud22/Dlib_Windows_Python3.x/blob/main/dlib-19.22.99-cp310-cp310-win_amd64.whl << Click Download RAW file and save to path "**webui_forge_cu121_torch21\system\python**"
3. Go to Path "**webui_forge_cu121_torch21\system\python**" and open `CMD` here with follow command: `python.exe -m pip install dlib-19.22.99-cp310-cp310-win_amd64.whl`
4. Done! open webui extras tab will show up extension
