### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ivanoff13** [Haoming02/sd-webui-old-photo-restoration#7]
Now you are processing dad-his-family-v0-o3cw61val1lc1.png
Running Stage 2: Face Detection
Traceback (most recent call last):
  File "C:\Users\djiva\Music\stable-diffusion-portable-main\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\djiva\Music\stable-diffusion-portable-main\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\djiva\Music\stable-diffusion-portable-main\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\djiva\Music\stable-diffusion-portable-main\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\djiva\Music\stable-diffusion-portable-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\djiva\Music\stable-diffusion-portable-main\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\djiva\Music\stable-diffusion-portable-main\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\djiva\Music\stable-diffusion-portable-main\extensions\sd-webui-old-photo-restoration\scripts\main_function.py", line 146, in bop
    final_output = core_functions(input_path, output_path, gpu_id, scratch, hr, face_res)
  File "C:\Users\djiva\Music\stable-diffusion-portable-main\extensions\sd-webui-old-photo-restoration\scripts\main_function.py", line 99, in core_functions
    detect_hr(['--url', stage1_results, '--save_url', stage2_output])
  File "C:\Users\djiva\Music\stable-diffusion-portable-main\extensions\sd-webui-old-photo-restoration\Face_Detection\detect_all_dlib_HR.py", line 140, in detect_hr
    landmark_locator = dlib.shape_predictor(landmark)
RuntimeError: Unable to open C:\Users\djiva\Music\stable-diffusion-portable-main\extensions\sd-webui-old-photo-restoration\Face_Detection\shape_predictor_68_face_landmarks.dat

**Comment by Haoming02** [comment]
Did you download the model?

**Comment by Haoming02** [comment]
*(assuming it's indeed just missing model)*
